/**
 * Build dist/ for Docker nginx + Cloudflare Pages.
 * Bundles ES modules into a single app.bundle.js (no build deps).
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  existsSync,
  rmSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");

// Ensure generated assets exist
spawnSync(process.execPath, [join(root, "scripts", "generate-ingredients.mjs")], {
  stdio: "inherit",
});
spawnSync(process.execPath, [join(root, "scripts", "generate-icons.mjs")], {
  stdio: "inherit",
});

if (existsSync(dist)) rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
mkdirSync(join(dist, "data"), { recursive: true });
mkdirSync(join(dist, "icons"), { recursive: true });

// Inline-bundle: convert ES modules to a single classic script (no type=module).
// Any leftover export/import *statements* throw and kill all UI handlers in Docker/Pages.
// Do not strip bare "export " text inside comments/strings (e.g. "export your grocery").
function stripModule(src) {
  return src
    // multi-line imports: import { a, b } from "./x.js";
    .replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"]\s*;?/g, "")
    .replace(/import\s+['"][^'"]+['"]\s*;?/g, "")
    .replace(/export\s+async\s+function\s+/g, "async function ")
    .replace(/export\s+function\s+/g, "function ")
    .replace(/export\s+const\s+/g, "const ")
    .replace(/export\s+let\s+/g, "let ")
    .replace(/export\s+var\s+/g, "var ")
    .replace(/export\s+class\s+/g, "class ")
    .replace(/export\s+default\s+/g, "")
    .replace(/export\s*\{[^}]*\}\s*;?/g, "");
}

const ingredients = stripModule(readFileSync(join(root, "data", "ingredients.js"), "utf8"));
const engine = stripModule(readFileSync(join(root, "src", "engine.js"), "utf8"));
const storage = stripModule(readFileSync(join(root, "src", "storage.js"), "utf8"));
const auth = stripModule(readFileSync(join(root, "src", "auth.js"), "utf8"));
const icons = stripModule(readFileSync(join(root, "src", "icons.js"), "utf8"));
const nutrition = stripModule(readFileSync(join(root, "src", "nutrition.js"), "utf8"));
const app = stripModule(readFileSync(join(root, "app.js"), "utf8"));

const bundle = `/* LiquidFloodie bundled build — generated by scripts/build.mjs */
${ingredients}
${engine}
${storage}
${auth}
${icons}
${nutrition}
${app}
`;

// Fail the build if leftover module *statements* would kill classic <script> (deployment killer).
// Note: English words like "export" in comments/strings are fine.
const leftoverModule = bundle.match(/(?:^|[\n;])\s*(?:export|import)\s+[\w*{]/m);
if (leftoverModule) {
  throw new Error(
    `Build refused: leftover module statement near "${leftoverModule[0].trim().slice(0, 40)}" — buttons would not work after deploy.`
  );
}
try {
  // eslint-disable-next-line no-new-func
  new Function(bundle);
} catch (err) {
  throw new Error(`Build refused: app.bundle.js is not valid classic JS: ${err.message}`);
}

writeFileSync(join(dist, "app.bundle.js"), bundle);

let html = readFileSync(join(root, "index.html"), "utf8");
html = html.replace(
  /<script\s+type="module"\s+src="app\.js"><\/script>/,
  '<script src="app.bundle.js" defer></script>'
);
writeFileSync(join(dist, "index.html"), html);

for (const f of ["styles.css", "sw.js", "manifest.webmanifest"]) {
  writeFileSync(join(dist, f), readFileSync(join(root, f)));
}
cpSync(join(root, "icons"), join(dist, "icons"), { recursive: true });
cpSync(join(root, "data", "ingredients.js"), join(dist, "data", "ingredients.js"));
if (existsSync(join(root, "public"))) {
  cpSync(join(root, "public"), dist, { recursive: true });
}
// Ensure liquid-diet background photo is present for Pages/Docker
const bgJpg = join(root, "public", "bg-liquid-diet.jpg");
if (existsSync(bgJpg)) {
  writeFileSync(join(dist, "bg-liquid-diet.jpg"), readFileSync(bgJpg));
}
const bgAlt = join(root, "public", "The-Liquid-Diet.jpg");
if (existsSync(bgAlt)) {
  writeFileSync(join(dist, "The-Liquid-Diet.jpg"), readFileSync(bgAlt));
}

// API docs stub for Cloudflare / Docker static hosting
writeFileSync(
  join(dist, "api.json"),
  JSON.stringify(
    {
      name: "LiquidFloodie Web API",
      version: "1.0.0",
      note: "Client-side SPA; optional Node API via `npm run api` (server/index.mjs). Endpoints mirror storage actions.",
      endpoints: [
        "GET /api/health",
        "GET /api/ingredients?q=",
        "GET /api/meal-plan",
        "POST /api/meal-plan/generate",
        "GET /api/grocery-list",
        "POST /api/export",
        "POST /api/import",
      ],
    },
    null,
    2
  )
);

console.log("Build complete → dist/");
