/**
 * Build dist/ for Docker nginx + Cloudflare Pages.
 * Bundles ES modules into a single app.bundle.js (no build deps).
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  existsSync,
  rmSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");

// Ensure generated assets exist
spawnSync(process.execPath, [join(root, "scripts", "generate-ingredients.mjs")], {
  stdio: "inherit",
});
spawnSync(process.execPath, [join(root, "scripts", "generate-icons.mjs")], {
  stdio: "inherit",
});

if (existsSync(dist)) rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
mkdirSync(join(dist, "data"), { recursive: true });
mkdirSync(join(dist, "icons"), { recursive: true });

// Inline-bundle: convert export modules to IIFE globals for zero-tooling browsers
function stripModule(src) {
  return src
    .replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*/g, "")
    .replace(/^export\s+async\s+function\s+/gm, "async function ")
    .replace(/^export\s+function\s+/gm, "function ")
    .replace(/^export\s+const\s+/gm, "const ")
    .replace(/^export\s+\{[^}]+\};?\s*/gm, "")
    .replace(/^export\s+default\s+/gm, "");
}

const ingredients = readFileSync(join(root, "data", "ingredients.js"), "utf8")
  .replace(/^export const INGREDIENT_DB = /, "const INGREDIENT_DB = ")
  .replace(/^export default INGREDIENT_DB;\s*$/m, "");
const engine = stripModule(readFileSync(join(root, "src", "engine.js"), "utf8"));
const storage = stripModule(readFileSync(join(root, "src", "storage.js"), "utf8"));
const auth = stripModule(readFileSync(join(root, "src", "auth.js"), "utf8"));
const icons = stripModule(readFileSync(join(root, "src", "icons.js"), "utf8"));
const nutrition = stripModule(readFileSync(join(root, "src", "nutrition.js"), "utf8"));
const app = stripModule(readFileSync(join(root, "app.js"), "utf8"));

const bundle = `/* LiquidFloodie bundled build — generated by scripts/build.mjs */
${ingredients}
${engine}
${storage}
${auth}
${icons}
${nutrition}
${app}
`;

writeFileSync(join(dist, "app.bundle.js"), bundle);

let html = readFileSync(join(root, "index.html"), "utf8");
html = html.replace(
  /<script\s+type="module"\s+src="app\.js"><\/script>/,
  '<script src="app.bundle.js" defer></script>'
);
writeFileSync(join(dist, "index.html"), html);

for (const f of ["styles.css", "sw.js", "manifest.webmanifest"]) {
  writeFileSync(join(dist, f), readFileSync(join(root, f)));
}
cpSync(join(root, "icons"), join(dist, "icons"), { recursive: true });
cpSync(join(root, "data", "ingredients.js"), join(dist, "data", "ingredients.js"));
if (existsSync(join(root, "public"))) {
  cpSync(join(root, "public"), dist, { recursive: true });
}

// API docs stub for Cloudflare / Docker static hosting
writeFileSync(
  join(dist, "api.json"),
  JSON.stringify(
    {
      name: "LiquidFloodie Web API",
      version: "1.0.0",
      note: "Client-side SPA; optional Node API via `npm run api` (server/index.mjs). Endpoints mirror storage actions.",
      endpoints: [
        "GET /api/health",
        "GET /api/ingredients?q=",
        "GET /api/meal-plan",
        "POST /api/meal-plan/generate",
        "GET /api/grocery-list",
        "POST /api/export",
        "POST /api/import",
      ],
    },
    null,
    2
  )
);

console.log("Build complete → dist/");
